### ISSUE TITLE
Cinnamon 5.4 reports that the extension isn't loading properly

### ISSUE THREAD

**Issue by mfreeman72** [hermes83/compiz-windows-effect-cinnamon#3]
I've updated to Linux Mint 21, and Cinnamon 5.4 reports that this extension isn't loading properly. However, it still seems to be functioning. I just get this notification every time I log in.

**Comment by hermes83** [comment]
should be fixed with the last commit a77f6d4b9f0c0f81312ae49faa99d0fa8be488c0
