### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by freonheat** [hermes83/compiz-windows-effect-cinnamon#4]
I just wanted to thank you for this- it brings back great memories :)
Works very well in Mint 21.
 
You should be featured here: 
https://cinnamon-spices.linuxmint.com/extensions
https://github.com/linuxmint/cinnamon-spices-extensions

so other people will find it.  Especially since the similar one there called "Wobbly Windows" is broken

**Comment by hermes83** [comment]
First of all, thanks for the nice words.
I opened a pull request on cinnamon-spices-extension several months ago (May 8):

[https://github.com/linuxmint/cinnamon-spices-extensions/pull/379](https://github.com/linuxmint/cinnamon-spices-extensions/pull/379)

unfortunately no one took charge of the request.
